#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : Introduction to Cultural Analytics & Python  # The title of the book. Will be placed in the left navbar.
author                      : <a href="https://melaniewalsh.org/">Melanie Walsh</a>  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : "images/logo/favicon.ico"  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "**/in-progress", "**/other_files", "features", "scraps"]

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : True # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#######################################################################################
# Parse and render settings
parse:
  myst_extended_syntax: true
#######################################################################################
# HTML-specific settings
html:
  favicon                   : "images/logo/favicon.ico"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  #Will be displayed underneath the left navbar.
  extra_footer              : |
    <div>
    <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> This book is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>. The code is licensed under a <a href="https://choosealicense.com/licenses/gpl-3.0/#">GNU General Public License v3.0</a>.
    </div>

  google_analytics_id       : "UA-86905362-3"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://melaniewalsh.github.io/Intro-Cultural-Analytics"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false


#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
#  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
#  thebe                     : False  # Add a thebe button to pages (requires the repository to run on Binder)
#  colab_url                 : False # The URL of Google Colab (e.g., https://colab.research.google.com)

repository:
  url                       : https://github.com/melaniewalsh/Intro-Cultural-Analytics  # The URL to your book's repository
  path_to_book              : "book"  # A path to your book's folder, relative to the repository root.
  branch                    : "master"  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    #- https://cdn.plot.ly/plotly-2.4.1.min.js
    rediraffe_branch: 'master'
    rediraffe_redirects:

      Python/Installation.ipynb: 02-Python/01-Install-Python.ipynb
      Python/Python.ipynb: 02-Python/00-Python.ipynb
      Python/Python.ipynb: 02-Python/00-Python.ipynb
      Python/Anatomy-Python-Script.ipynb: 02-Python/03-Anatomy-Python-Script.ipynb
      Python/Common-Python-Errors.ipynb: 02-Python/13-Common-Python-Errors.ipynb
      Python/Comparisons-Conditionals.ipynb: 02-Python/08-Comparisons-Conditionals.ipynb
      Python/Data-Types.ipynb: 02-Python/05-Data-Types.ipynb
      Python/Dictionaries.ipynb: 02-Python/11-Dictionaries.ipynb
      Python/Files-Character-Encoding.ipynb: 02-Python/07-Files-Character-Encoding.ipynb
      Python/Functions.ipynb: 02-Python/12-Functions.ipynb
      Python/How-to-Use-Jupyter-Notebooks.ipynb: 02-Python/02-How-to-Use-Jupyter-Notebooks.ipynb
      Python/Jupyter-Tips-Tricks.ipynb: 02-Python/EXTRA-Jupyter-Tips-Tricks.ipynb
      Python/Lists-Loops-Part1.ipynb: 02-Python/09-Lists-Loops-Part1.ipynb
      Python/Lists-Loops-Part2.ipynb: 02-Python/10-Lists-Loops-Part2.ipynb
      Python/Randomize-Students.ipynb: 02-Python/EXTRA-Randomize-Students.ipynb
      Python/String-Methods.ipynb: 02-Python/06-String-Methods.ipynb
      Python/Variables.ipynb: 02-Python/04-Variables.ipynb
      Python/What-Were-Not-Covering.ipynb: 02-Python/14-What-Were-Not-Covering.ipynb
      Command-Line/Command-Line: 01-Command-Line/01-The-Command-Line
      Data-Analysis/Pandas-Merge-Datasets.ipynb: 03-Data-Analysis/04-Pandas-Merge-Datasets.ipynb
      Data-Analysis/Pandas-Basics-Part3.ipynb: 03-Data-Analysis/03-Pandas-Basics-Part3.ipynb
      Data-Analysis/Pandas-Basics-Part1.ipynb: 03-Data-Analysis/01-Pandas-Basics-Part1.ipynb
      Data-Analysis/Pandas-Basics-Part2.ipynb: 03-Data-Analysis/02-Pandas-Basics-Part2.ipynb
      Data-Analysis/Data-Analysis.ipynb: 03-Data-Analysis/00-Data-Analysis.ipynb
      Text-Analysis/TF-IDF: 05-Text-Analysis/01-TF-IDF
      Text-Analysis/TF-IDF-HathiTrust: 05-Text-Analysis/02-TF-IDF-HathiTrust
      Text-Analysis/TF-IDF-Scikit-Learn: 05-Text-Analysis/03-TF-IDF-Scikit-Learn
      Text-Analysis/Topic-Modeling: 05-Text-Analysis/05-Topic-Modeling
      Text-Analysis/Topic-Modeling-Overview: 05-Text-Analysis/06-Topic-Modeling-Overview
      Text-Analysis/Topic-Modeling-Set-Up: 05-Text-Analysis/07-Topic-Modeling-Set-Up
      Text-Analysis/Topic-Modeling-Text-Files: 05-Text-Analysis/08-Topic-Modeling-Text-Files
      Text-Analysis/Topic-Modeling-CSV: 05-Text-Analysis/10-Topic-Modeling-CSV
      Text-Analysis/Topic-Modeling-Time-Series: 05-Text-Analysis/11-Topic-Modeling-Time-Series
      Text-Analysis/Named-Entity-Recognition: 05-Text-Analysis/12-Named-Entity-Recognition
      Text-Analysis/POS-Keywords: 05-Text-Analysis/13-POS-Keywords
      Network-Analysis/Network-Analysis-Home: 06-Network-Analysis/00-Network-Analysis
      Network-Analysis/Network-Analysis: 06-Network-Analysis/01-Network-Analysis
      Network-Analysis/Making-Network-Viz-with-Bokeh: 06-Network-Analysis/02-Making-Network-Viz-with-Bokeh
      Data-Collection/Data-Collection: 04-Data-Collection/00-Data-Collection
      Data-Collection/User-Ethics-Legal-Concerns: 04-Data-Collection/01-User-Ethics-Legal-Concerns
      Data-Collection/Web-Scraping-Part1: 04-Data-Collection/02-Web-Scraping-Part1
      Data-Collection/Web-Scraping-Part2: 04-Data-Collection/03-Web-Scraping-Part2
      Data-Collection/Git-GitHub: 04-Data-Collection/04-Git-GitHub
      Data-Collection/APIs: 04-Data-Collection/05-What-Is-API
      Data-Collection/Song-Genius-Data-Collection: 04-Data-Collection/06-Song-Genius
      Data-Collection/Genius-API: 04-Data-Collection/07-Genius-API
      Data-Collection/LyricsGenius: 04-Data-Collection/08-Collect-Genius-Lyrics
      Data-Collection/LyricsGenius: 04-Data-Collection/09-Lyrics-Analysis
      Data-Collection/Twitter-Data-Collection-Home: 04-Data-Collection/10-Twitter
      Data-Collection/Twitter-API-Setup: 04-Data-Collection/11-Twitter-API-Setup
      Data-Collection/Twitter-Data-Collection: 04-Data-Collection/12-Twitter-Data
      Data-Collection/Twitter-Data-Sharing: 04-Data-Collection/13-Twitter-Data-Sharing
      Data-Collection/Reddit-Data-Collection-with-PSAW: 04-Data-Collection/14-Reddit-Data
      Mapping/Publish-Your-Map: 07-Mapping/03-Publish-Your-Map
      Mapping/Mapping:  07-Mapping/01-Mapping
      Mapping/Mapping-Home: 07-Mapping/00-Mapping
      Mapping/Custom-Maps: 07-Mapping/02-Custom-Maps
      Datasets/Datasets: 00-Datasets/00-Datasets

    myst_enable_extensions:
      - html_admonition
      - amsmath
      - colon_fence
      - deflist
      - dollarmath
      - html_image
      - replacements
      - smartquotes
      - substitution
    notfound_context:
        body: "<h1>Whoops! Page Not Found</h1>\n\n<p>Sorry, this page doesn't exist. Many sections of this book have been updated recently.</p><p>Try the <a href='https://melaniewalsh.github.io/Intro-Cultural-Analytics/index.html'>home page 🏠 </a> or <a href='https://melaniewalsh.github.io/Intro-Cultural-Analytics/search.html'>search page 🔎 </a> to find what you're looking for.</p>"
    notfound_urls_prefix: "/Intro-Cultural-Analytics/"

  extra_extensions:
    - notfound.extension
    - sphinxext.rediraffe
